function(auras)
    local spells = aura_env.Spells
    aura_env.Update(auras, function()
        return (aura_env.DotRemainingTime(spells.FrostFever) < 3 and aura_env.Cast(spells.IcyTouch))
        or (aura_env.DotRemainingTime(spells.BloodPlague) < 3 and aura_env.Cast(spells.PlagueStrike))
        or (not aura_env.AuraIsActive(spells.Desolation) and aura_env.Cast(spells.BloodStrike))
        or ((aura_env.AuraIsActive(spells.SummonGargoyle) or aura_env.TimeToReady(spells.SummonGargoyle) > 50) and aura_env.Cast(spells.Gloves))
        or (aura_env.AuraIsActive(spells.SummonGargoyle) and aura_env.Cast(spells.PotionOfSpeed))
        or (aura_env.AuraIsActive(spells.SummonGargoyle)
            and not aura_env.IsReady(spells.EmpowerRuneWeapon)
            and aura_env.NumNonDeathRunes(aura_env.RuneType.Frost) == 1
            and aura_env.Cast(spells.ArmyOfTheDead))
        or (not aura_env.AuraIsActive(spells.UnholyForce) and aura_env.IsReady(spells.SummonGargoyle) and aura_env.Cast(spells.ScourgeStrike))
        or aura_env.Cast(spells.DeathAndDecay)
        or (aura_env.AuraIsActive(spells.SummonGargoyle) and aura_env.Cast(spells.ArmyOfTheDead))
        or (aura_env.TimeToReady(spells.DeathAndDecay) > 6 and aura_env.Cast(spells.ScourgeStrike))
        or ((aura_env.TimeToReady(spells.DeathAndDecay) > 6 or aura_env.IsReady(spells.EmpowerRuneWeapon))
            and (aura_env.AuraRemainingTime(spells.Desolation) < 10 or aura_env.AuraRemainingICD(spells.UnholyMight) <= 0)
            and aura_env.Cast(spells.BloodStrike))
        or ((aura_env.TimeToReady(spells.DeathAndDecay) > 6 or aura_env.IsReady(spells.EmpowerRuneWeapon)) and aura_env.Cast(spells.BloodBoil))
        or (aura_env.AuraIsActive(spells.SummonGargoyle) and aura_env.Cast(spells.EmpowerRuneWeapon))
        or aura_env.Cast(spells.SummonGargoyle)
        or (not aura_env.IsReady(spells.SummonGargoyle) and aura_env.Cast(spells.DeathCoil))
        or (aura_env.IsReady(spells.BloodTap) and aura_env.IsReady(spells.GhoulFrenzy) and not aura_env.AuraIsActivePet(spells.GhoulFrenzy) and (aura_env.Cast(spells.BloodTap) or aura_env.Cast(spells.GhoulFrenzy)))
        or (aura_env.AuraIsActive(spells.UnholyPresence) and not aura_env.IsReady(spells.SummonGargoyle) and not aura_env.AuraIsActive(spells.SummonGargoyle) and aura_env.Cast(spells.BloodPresence))
        or aura_env.Cast(spells.HornOfWinter)
    end)
    return true
end

